import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.dirname(fileURLToPath(import.meta.url));
let html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"style.css"),"utf8");
html=html.replace('<link rel="stylesheet" href="style.css">',`<style>\n${css}\n</style>`);
html=html.replace(/src="(assets\/[^\"]+)"/g,(_m,rel)=>{const optimizedRel=rel.replace("assets/","assets-optimized/");const file=path.join(root,optimizedRel.replaceAll("/",path.sep));const ext=path.extname(file).toLowerCase();const mime=ext===".png"?"image/png":"image/jpeg";return `src="data:${mime};base64,${fs.readFileSync(file).toString("base64")}"`;});
fs.writeFileSync(path.join(root,"unified_portfolio_inline.html"),html,"utf8");
console.log(path.join(root,"unified_portfolio_inline.html"));
